import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "ScriptMind AI Privacy Policy — how we collect, use, and protect your data.",
};

const sections = [
  {
    title: "1. Information We Collect",
    body: `We collect information you provide directly (name, email, payment info), information generated by your use of the service (scripts, prompts, analysis results), and standard usage data (IP address, browser type, pages visited, timestamps).`,
  },
  {
    title: "2. How We Use Your Information",
    body: `We use your information to provide and improve the service, authenticate your identity, process payments, send transactional emails, and comply with legal obligations. We do not sell your personal data to third parties.`,
  },
  {
    title: "3. AI Processing",
    body: `Content you submit for AI analysis (scripts, story premises, dialogue) is processed by our AI models to generate results. We may use anonymised, aggregated inputs to improve model quality. We do not use your content to train third-party models without your consent.`,
  },
  {
    title: "4. Data Sharing",
    body: `We may share data with trusted service providers (cloud hosting, payment processors, analytics) under strict confidentiality agreements. We may disclose data if required by law. We will never sell your personal information.`,
  },
  {
    title: "5. Authentication & Cookies",
    body: `We use Supabase for authentication and session management. Session tokens are stored in secure HTTP-only cookies. We may use first-party analytics cookies to understand platform usage. You can manage cookie preferences in your browser settings.`,
  },
  {
    title: "6. Data Retention",
    body: `We retain your account data for as long as your account is active. You may request deletion of your account and associated data at any time by contacting support. Anonymised usage data may be retained for analytics purposes.`,
  },
  {
    title: "7. Security",
    body: `We implement industry-standard security measures including encrypted data transmission (TLS), hashed passwords, and access controls. No system is completely secure; we encourage you to use a strong, unique password.`,
  },
  {
    title: "8. Your Rights",
    body: `Depending on your location, you may have rights to access, correct, or delete your personal data, or object to certain processing. Contact us at support@scriptmind.ai to exercise these rights.`,
  },
  {
    title: "9. Third-Party Links",
    body: `Our platform may contain links to third-party websites. We are not responsible for the privacy practices of those sites. We encourage you to review their privacy policies.`,
  },
  {
    title: "10. Changes to This Policy",
    body: `We may update this Privacy Policy periodically. We will notify you of material changes via email or a prominent notice on the platform. Continued use after changes constitutes acceptance of the revised policy.`,
  },
  {
    title: "11. Contact Us",
    body: `If you have questions about this Privacy Policy or your personal data, please contact us at support@scriptmind.ai or write to: ScriptMind AI, Mumbai, Maharashtra, India.`,
  },
];

export default function PrivacyPage() {
  return (
    <div className="min-h-screen pt-24 pb-20 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="mb-12 text-center">
          <h1 className="text-4xl font-black text-white mb-4">Privacy Policy</h1>
          <p className="text-text-muted text-sm">Last updated: April 2025</p>
          <div className="mt-6 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />
        </div>

        <p className="text-text-secondary leading-relaxed mb-10">
          Your privacy matters to us. This policy explains what data ScriptMind AI collects, why we
          collect it, and how we keep it safe.
        </p>

        {/* Sections */}
        <div className="space-y-8">
          {sections.map((s) => (
            <section key={s.title}>
              <h2 className="text-lg font-bold text-white mb-2">{s.title}</h2>
              <p className="text-text-secondary leading-relaxed text-sm">{s.body}</p>
            </section>
          ))}
        </div>

        {/* Footer nav */}
        <div className="mt-14 pt-8 border-t border-white/10 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-text-muted">
          <span>Questions? Email us at{" "}
            <a href="mailto:support@scriptmind.ai" className="text-accent hover:underline">
              support@scriptmind.ai
            </a>
          </span>
          <div className="flex gap-6">
            <Link href="/terms" className="hover:text-white transition-colors">Terms of Service</Link>
            <Link href="/support" className="hover:text-white transition-colors">Support</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
