import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "ScriptMind AI Terms of Service — understand how you may use our platform.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    body: `By accessing or using ScriptMind AI ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, please do not use the Platform.`,
  },
  {
    title: "2. Description of Service",
    body: `ScriptMind AI provides AI-powered tools for Bollywood screenwriters, including script analysis, story generation, dialogue creation, revenue projection, and related creative assistance features.`,
  },
  {
    title: "3. User Accounts",
    body: `You must provide accurate information when creating an account. You are responsible for maintaining the confidentiality of your credentials and for all activity that occurs under your account.`,
  },
  {
    title: "4. Acceptable Use",
    body: `You agree not to use the Platform to generate content that is illegal, harmful, defamatory, or infringes third-party intellectual property rights. ScriptMind AI reserves the right to suspend accounts that violate these terms.`,
  },
  {
    title: "5. Intellectual Property",
    body: `Content you create using the Platform belongs to you. You grant ScriptMind AI a limited, non-exclusive licence to process your inputs solely to deliver the service. Our platform code, AI models, and branding remain the property of ScriptMind AI.`,
  },
  {
    title: "6. AI-Generated Content",
    body: `Outputs generated by our AI are provided for creative assistance only. ScriptMind AI does not guarantee the accuracy, originality, or legal clearance of AI-generated content. You are responsible for reviewing outputs before use.`,
  },
  {
    title: "7. Subscription & Billing",
    body: `Paid plans are billed in advance on a monthly or annual basis. Refunds are subject to our refund policy. We reserve the right to modify pricing with 30 days' notice.`,
  },
  {
    title: "8. Disclaimers",
    body: `The Platform is provided "as is" without warranties of any kind. ScriptMind AI shall not be liable for any indirect, incidental, or consequential damages arising from use of the service.`,
  },
  {
    title: "9. Changes to Terms",
    body: `We may update these Terms from time to time. Continued use of the Platform after changes constitutes acceptance of the new Terms. The "Last updated" date at the bottom of this page reflects the most recent revision.`,
  },
  {
    title: "10. Governing Law",
    body: `These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive jurisdiction of the courts of Mumbai, Maharashtra.`,
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-24 pb-20 px-4">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="mb-12 text-center">
          <h1 className="text-4xl font-black text-white mb-4">Terms of Service</h1>
          <p className="text-text-muted text-sm">Last updated: April 2025</p>
          <div className="mt-6 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent" />
        </div>

        <p className="text-text-secondary leading-relaxed mb-10">
          Please read these Terms of Service carefully before using ScriptMind AI. These terms govern
          your access to and use of our platform and services.
        </p>

        {/* Sections */}
        <div className="space-y-8">
          {sections.map((s) => (
            <section key={s.title}>
              <h2 className="text-lg font-bold text-white mb-2">{s.title}</h2>
              <p className="text-text-secondary leading-relaxed text-sm">{s.body}</p>
            </section>
          ))}
        </div>

        {/* Footer nav */}
        <div className="mt-14 pt-8 border-t border-white/10 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-text-muted">
          <span>Questions? Email us at{" "}
            <a href="mailto:support@scriptmind.ai" className="text-accent hover:underline">
              support@scriptmind.ai
            </a>
          </span>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-white transition-colors">Privacy Policy</Link>
            <Link href="/support" className="hover:text-white transition-colors">Support</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
